meta_product_name: "Twosty"
meta_title: "Twosty - Where good food meets fun dates"
meta_description: "Twosty is a dating app matching people simply over their meal preference"
meta_image: "social.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
